### ISSUE TITLE
there is no issue, i simply love markus

### ISSUE THREAD

**Issue by wheremichaelgo** [Mezque/markus#1]
i love markus, and every person in the world should markus. He is such a lovable, wholesome, aweosme little fealla, and deserves the wordl. I want markus to be with me for th e rest of my life and i love markus
<3

**Comment by Mezque** [comment]
thank you - signed markus the cat 
![mark](https://user-images.githubusercontent.com/31026406/146647657-8f69939d-eb04-4ce6-8b76-34845a97ccb9.png)
